#!/usr/bin/env python3
import sys
import subprocess


def terminate(reason, code=1):
    print(reason)
    exit(code)


dbpath = sys.argv[1] if len(sys.argv) > 1 else terminate("no db provided")

provider = sys.argv[2] if len(sys.argv) > 2 else "sqlite"

print(dbpath, provider)

cmd = "termdbms" if subprocess.run(
    "termdbms", shell=True).returncode != 127 else "~/go/bin/termdbms"
print(cmd)
subprocess.run(f'{cmd} -p {dbpath} -d {provider}', shell=True)
